version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest

jobs:

  install:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - checkout
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: ⬇️ Installing...
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .

  check:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: ☣️ Check danger...
          command: .ci/check_danger.sh
      - run: 
          name: 🏁 Check formatting...
          command: .ci/check_formating.sh
      - run: 
          name: 📋 Check linting...
          command: .ci/check_linting.sh
      - run: 
          name: 🔳 Check types...
          command: .ci/check_types.sh
      - run: 
          name: ✅ Check tests...
          command: .ci/check_tests.sh

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: 🏗 Building
          command: .ci/build.sh
      - persist_to_workspace:
          root: .
          paths: .

  publish:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: 🚀 Deploy
          command: .ci/version_and_publish.sh

  publish:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: ⬆️ Publishing
          command: .ci/version_and_publish.sh

workflows:
  version: 2
  default:
    jobs:
      - install
      - check:
          requires: 
            - install
      - build:
          requires: 
            - install
      - deploy:
          requires: 
            - check
            - build
      - publish:
          requires: 
            - check
            - build
          filters:
            branches:
              only:
                - master
